spring.application.name=taskManager
jwt.key=def4bc89cf84909e751beca8d242b51b53c736cb72750874341ab3b056a5b097

spring.datasource.url= jdbc:postgresql://localhost:5433/task_manager_db
spring.datasource.username=task_admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.show-sql=true